apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-cleanup-cronjob
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: minio-cleanup
            image: <your image>
            imagePullPolicy: Always
            env:
            - name: ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-credential
                  key: ENDPOINT
            - name: ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: minio-credential
                  key: ACCESS_KEY_ID
            - name: SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio-credential
                  key: SECRET_ACCESS_KEY
            - name: BUCKETNAME
              value: chunks
            - name: RETENTIONPERIOD
              # value must be quoted
              value: "7"
          restartPolicy: Never
