apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-cleanup-cronjob
  namespace: lgtm
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: minio-cleanup
            image: <your image>
            imagePullPolicy: Always
            env:
            - name: ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: minio-credential
                  key: ACCESS_KEY_ID
            - name: SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: minio-credential
                  key: SECRET_ACCESS_KEY
          restartPolicy: Never
